d={'employee_id': 'EMP005',
'full_name': 'Karthik Nair',
'email': 'karthik.nair@company.com',
'phone_number': '+91-5432109876',
'date_of_birth': '2000-05-18',
'joining_date': '2025-02-15',
'training_start_date': '2025-02-18',
'training_end_date': '2025-04-18',
'salary': '590000',
'bonus_percentage': '13.2',
'primary_skillset': 'Mobile Development',
'secondary_skills': 'Flutter, React Native, Swift',
'years_of_experience': '0.3',
'college_cgpa': '8.6',
'is_training_complete': 'FALSE',
'is_deployment_ready': 'FALSE',
'project_assigned': 'Project Delta',
'deployment_date': '',
'manager_name': 'Lakshmi Iyer',
'location': 'Pune',
'department': 'Mobile',
'certification_count': '1',
'active_certifications': 'Google Associate Android Developer',
'pending_certifications': 'iOS Developer Certification, Flutter Certified',
'performance_rating': '3.7',
'training_hours': '380',
'billable_hours_target': '170',
'current_billable_hours': '29',
'training_cost': '70000',
'comments': 'Innovative thinking, eager to learn new technologies',
'emergency_contact_name': 'Rekha Nair',
'emergency_contact_phone': '+91-5432109877',
'blood_group': 'B-',
'employee_photo_path': '/photos/karthik_nair.jpg',
'resume_path': '/resumes/karthik_nair.pdf',
'offer_letter_date': '2024-12-05',
'background_verification_status': 'Completed',
'medical_checkup_complete': 'TRUE',
'laptop_assigned': 'TRUE',
'asset_tag_number': 'LT004',
'workstation_number': 'WS-108',
'reporting_time': '09:15:00',
'access_card_number': 'AC12348',
'parking_slot': 'P-89',
'team_size': '5',
'project_duration_months': '18',
'client_feedback_score': '',
'training_feedback': 'Shows great potential in mobile development',
'internal_rating': '7.9',
'promotion_eligible': 'FALSE',
'last_appraisal_date': '2025-01-01',
'next_appraisal_date': '2026-01-01',
'stock_options_granted': '250',
'relocation_required': 'TRUE',
'accommodation_provided': 'FALSE',
'transport_allowance': '2800',
'health_insurance_enrolled': 'TRUE',
'life_insurance_amount': '550000',
'pf_account_number': 'PF321654987',
'bank_account_number': '3216549876543210',
'ifsc_code': 'PNB0005678',
'pan_number': 'XYZAB6789J',
'aadhar_number': '321654987321',
'passport_number': 'P3216549',
'visa_status': 'Not Required',
'work_authorization': 'Indian Citizen',
'previous_company': 'Cognizant',
'notice_period_days': '75',
'reference_check_status': 'Completed',
'social_media_linked_in': 'https://linkedin.com/in/kartiknair',
'git_hub_profile': 'https://github.com/kartiknair',
'technical_blog_url': 'https://mobiledev.wordpress.com',
'hobbies': 'Swimming, Movies, Technology',
'languages_known': 'Malayalam, English, Hindi',
'project_preferences': 'Cross-platform Development, UI/UX',
'career_goals': 'Mobile Architect in 4 years',
'mentor_assigned': 'FALSE',
'mentor_name': '',
'onboarding_buddy': 'Pooja Sharma',
'training_batch': 'Batch-2025-Feb',
'probation_period_months': '6',
'confirmation_date': '',
'exit_interview_required': 'FALSE',
'resignation_date': '',
'last_working_day': '',
'rehire_eligible': 'TRUE'}

from collections import namedtuple

def dict_to_namedtuple(name, d):
    NT = namedtuple(name, d.keys())
    return NT(**d)


row_nt = dict_to_namedtuple('Row', d)
print(row_nt.exit_interview_required)  # 1
print(row_nt.career_goals)  # 2