-- CreateTable
CREATE TABLE "Crs" (
    "id" TEXT NOT NULL,
    "employee_id" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "joining_date" TIMESTAMP(3) NOT NULL,
    "training_start_date" TIMESTAMP(3) NOT NULL,
    "training_end_date" TIMESTAMP(3) NOT NULL,
    "salary" TIMESTAMP(3) NOT NULL,
    "bonus_percentage" DOUBLE PRECISION NOT NULL,
    "primary_skillset" TEXT NOT NULL,
    "secondary_skills" TEXT NOT NULL,
    "years_of_experience" DOUBLE PRECISION NOT NULL,
    "college_cgpa" DOUBLE PRECISION NOT NULL,
    "is_training_complete" BOOLEAN NOT NULL,
    "is_deployment_ready" BOOLEAN NOT NULL,
    "project_assigned" TEXT NOT NULL,
    "deployment_date" TIMESTAMP(3) NOT NULL,
    "manager_name" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "certification_count" TIMESTAMP(3) NOT NULL,
    "active_certifications" TEXT NOT NULL,
    "pending_certifications" TEXT NOT NULL,
    "performance_rating" DOUBLE PRECISION NOT NULL,
    "training_hours" TIMESTAMP(3) NOT NULL,
    "billable_hours_target" TIMESTAMP(3) NOT NULL,
    "current_billable_hours" TIMESTAMP(3) NOT NULL,
    "training_cost" TIMESTAMP(3) NOT NULL,
    "comments" TEXT NOT NULL,
    "emergency_contact_name" TEXT NOT NULL,
    "emergency_contact_phone" TEXT NOT NULL,
    "blood_group" TEXT NOT NULL,
    "employee_photo_path" TEXT NOT NULL,
    "resume_path" TEXT NOT NULL,
    "offer_letter_date" TIMESTAMP(3) NOT NULL,
    "background_verification_status" TEXT NOT NULL,
    "medical_checkup_complete" BOOLEAN NOT NULL,
    "laptop_assigned" BOOLEAN NOT NULL,
    "asset_tag_number" TEXT NOT NULL,
    "workstation_number" TEXT NOT NULL,
    "reporting_time" TIMESTAMP(3) NOT NULL,
    "access_card_number" TEXT NOT NULL,
    "parking_slot" TEXT NOT NULL,
    "team_size" TIMESTAMP(3) NOT NULL,
    "project_duration_months" TIMESTAMP(3) NOT NULL,
    "client_feedback_score" TIMESTAMP(3) NOT NULL,
    "training_feedback" TEXT NOT NULL,
    "internal_rating" DOUBLE PRECISION NOT NULL,
    "promotion_eligible" BOOLEAN NOT NULL,
    "last_appraisal_date" TIMESTAMP(3) NOT NULL,
    "next_appraisal_date" TIMESTAMP(3) NOT NULL,
    "stock_options_granted" TIMESTAMP(3) NOT NULL,
    "relocation_required" BOOLEAN NOT NULL,
    "accommodation_provided" BOOLEAN NOT NULL,
    "transport_allowance" TIMESTAMP(3) NOT NULL,
    "health_insurance_enrolled" BOOLEAN NOT NULL,
    "life_insurance_amount" TIMESTAMP(3) NOT NULL,
    "pf_account_number" TEXT NOT NULL,
    "bank_account_number" TIMESTAMP(3) NOT NULL,
    "ifsc_code" TEXT NOT NULL,
    "pan_number" TEXT NOT NULL,
    "aadhar_number" TIMESTAMP(3) NOT NULL,
    "passport_number" TEXT NOT NULL,
    "visa_status" TEXT NOT NULL,
    "work_authorization" TEXT NOT NULL,
    "previous_company" TEXT NOT NULL,
    "notice_period_days" TIMESTAMP(3) NOT NULL,
    "reference_check_status" TEXT NOT NULL,
    "social_media_linked_in" TEXT NOT NULL,
    "git_hub_profile" TEXT NOT NULL,
    "technical_blog_url" TEXT NOT NULL,
    "hobbies" TEXT NOT NULL,
    "languages_known" TEXT NOT NULL,
    "project_preferences" TEXT NOT NULL,
    "career_goals" TEXT NOT NULL,
    "mentor_assigned" BOOLEAN NOT NULL,
    "mentor_name" TEXT NOT NULL,
    "onboarding_buddy" TEXT NOT NULL,
    "training_batch" TEXT NOT NULL,
    "probation_period_months" TIMESTAMP(3) NOT NULL,
    "confirmation_date" TIMESTAMP(3) NOT NULL,
    "exit_interview_required" BOOLEAN NOT NULL,
    "resignation_date" BOOLEAN NOT NULL,
    "last_working_day" BOOLEAN NOT NULL,
    "rehire_eligible" BOOLEAN NOT NULL,

    CONSTRAINT "Crs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CrsHistory" (
    "surrogate_key" TEXT NOT NULL,
    "employee_id" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "joining_date" TIMESTAMP(3) NOT NULL,
    "training_start_date" TIMESTAMP(3) NOT NULL,
    "training_end_date" TIMESTAMP(3) NOT NULL,
    "salary" TIMESTAMP(3) NOT NULL,
    "bonus_percentage" DOUBLE PRECISION NOT NULL,
    "primary_skillset" TEXT NOT NULL,
    "secondary_skills" TEXT NOT NULL,
    "years_of_experience" DOUBLE PRECISION NOT NULL,
    "college_cgpa" DOUBLE PRECISION NOT NULL,
    "is_training_complete" BOOLEAN NOT NULL,
    "is_deployment_ready" BOOLEAN NOT NULL,
    "project_assigned" TEXT NOT NULL,
    "deployment_date" TIMESTAMP(3) NOT NULL,
    "manager_name" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "certification_count" TIMESTAMP(3) NOT NULL,
    "active_certifications" TEXT NOT NULL,
    "pending_certifications" TEXT NOT NULL,
    "performance_rating" DOUBLE PRECISION NOT NULL,
    "training_hours" TIMESTAMP(3) NOT NULL,
    "billable_hours_target" TIMESTAMP(3) NOT NULL,
    "current_billable_hours" TIMESTAMP(3) NOT NULL,
    "training_cost" TIMESTAMP(3) NOT NULL,
    "comments" TEXT NOT NULL,
    "emergency_contact_name" TEXT NOT NULL,
    "emergency_contact_phone" TEXT NOT NULL,
    "blood_group" TEXT NOT NULL,
    "employee_photo_path" TEXT NOT NULL,
    "resume_path" TEXT NOT NULL,
    "offer_letter_date" TIMESTAMP(3) NOT NULL,
    "background_verification_status" TEXT NOT NULL,
    "medical_checkup_complete" BOOLEAN NOT NULL,
    "laptop_assigned" BOOLEAN NOT NULL,
    "asset_tag_number" TEXT NOT NULL,
    "workstation_number" TEXT NOT NULL,
    "reporting_time" TIMESTAMP(3) NOT NULL,
    "access_card_number" TEXT NOT NULL,
    "parking_slot" TEXT NOT NULL,
    "team_size" TIMESTAMP(3) NOT NULL,
    "project_duration_months" TIMESTAMP(3) NOT NULL,
    "client_feedback_score" TIMESTAMP(3) NOT NULL,
    "training_feedback" TEXT NOT NULL,
    "internal_rating" DOUBLE PRECISION NOT NULL,
    "promotion_eligible" BOOLEAN NOT NULL,
    "last_appraisal_date" TIMESTAMP(3) NOT NULL,
    "next_appraisal_date" TIMESTAMP(3) NOT NULL,
    "stock_options_granted" TIMESTAMP(3) NOT NULL,
    "relocation_required" BOOLEAN NOT NULL,
    "accommodation_provided" BOOLEAN NOT NULL,
    "transport_allowance" TIMESTAMP(3) NOT NULL,
    "health_insurance_enrolled" BOOLEAN NOT NULL,
    "life_insurance_amount" TIMESTAMP(3) NOT NULL,
    "pf_account_number" TEXT NOT NULL,
    "bank_account_number" TIMESTAMP(3) NOT NULL,
    "ifsc_code" TEXT NOT NULL,
    "pan_number" TEXT NOT NULL,
    "aadhar_number" TIMESTAMP(3) NOT NULL,
    "passport_number" TEXT NOT NULL,
    "visa_status" TEXT NOT NULL,
    "work_authorization" TEXT NOT NULL,
    "previous_company" TEXT NOT NULL,
    "notice_period_days" TIMESTAMP(3) NOT NULL,
    "reference_check_status" TEXT NOT NULL,
    "social_media_linked_in" TEXT NOT NULL,
    "git_hub_profile" TEXT NOT NULL,
    "technical_blog_url" TEXT NOT NULL,
    "hobbies" TEXT NOT NULL,
    "languages_known" TEXT NOT NULL,
    "project_preferences" TEXT NOT NULL,
    "career_goals" TEXT NOT NULL,
    "mentor_assigned" BOOLEAN NOT NULL,
    "mentor_name" TEXT NOT NULL,
    "onboarding_buddy" TEXT NOT NULL,
    "training_batch" TEXT NOT NULL,
    "probation_period_months" TIMESTAMP(3) NOT NULL,
    "confirmation_date" TIMESTAMP(3) NOT NULL,
    "exit_interview_required" BOOLEAN NOT NULL,
    "resignation_date" BOOLEAN NOT NULL,
    "last_working_day" BOOLEAN NOT NULL,
    "rehire_eligible" BOOLEAN NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL,
    "end_date" TIMESTAMP(3),
    "is_current" BOOLEAN NOT NULL,

    CONSTRAINT "CrsHistory_pkey" PRIMARY KEY ("surrogate_key")
);
